### ISSUE TITLE
Path com/ggprison/apples/command does not end with com.ggprison.apples.command

### ISSUE THREAD

**Issue by imsnaily** [ColinGrime/Midnight#1]
Hey! I've been using your library (is awesome btw) for a plugin am I doing. But when I tried to run the plugin on my localhost, I ran with this issue. Im not sure if Im doing something wrong (i might).

<img width="1498" height="475" alt="Image" src="https://github.com/user-attachments/assets/02aa7465-9f81-4892-bdf9-2b12864f88d9" />

I'll leave here my plugin directory.

<img width="310" height="687" alt="Image" src="https://github.com/user-attachments/assets/761a8fa9-ae40-45a4-9047-428f1b469c44" />

This is my CustomApplesAdmin.java code:

```java

package com.ggprison.apples.command.customapple;

import com.ggprison.apples.CustomApples;
import com.ggprison.apples.config.Messages;

import me.colingrimes.midnight.command.Command;
import me.colingrimes.midnight.command.handler.util.CommandProperties;

public class CustomApplesAdmin implements Command<CustomApples> {
    @Override
    public void configureProperties(CommandProperties properties) {
        properties.setUsage(Messages.USAGE_APPLES);
        properties.setPermission("customapples.admin");
        properties.setAliases("apples", "customapples", "capples");
    }
}
```

**Comment by ColinGrime** [comment]
Thanks for the bug report!  I'll look into it sometime tomorrow and let you know what I find.

**Comment by imsnaily** [comment]
I swapped from maven to gradle just in case it was that lol but I still have the same error.
Path com/ggprison/apples/command does not end with com.ggprison.apples.command

**Comment by imsnaily** [comment]
Last thing that maybe helps. Tried to run your plugin "SkyMines" too, I got the same error as my plugin. So yeah is definitly an issue from the library directly.

<img width="1583" height="497" alt="Image" src="https://github.com/user-attachments/assets/08cfcff0-bdb1-425e-a92f-a9af7b66065b" />

**Comment by ColinGrime** [comment]
Yeah, my Windows PC was having problems yesterday, so I wasn't able to test it then - but I looked at the code and I'm pretty certain it just breaks on Windows operating systems.  I'm shocked the library has never been run on Windows before...

I'll get a fix out soon.

**Comment by imsnaily** [comment]
I can do a pr if you want for the fix, seems like I fixed it. I can't test it on linux, don't have a linux and Im too lazy to install a vm

**Comment by ColinGrime** [comment]
That would be great, thanks.  I'm still having a lot of problems with my Windows PC right now.  I can test it on my side to make sure it still works.

**Comment by imsnaily** [comment]
PR done

**Comment by ColinGrime** [comment]
Sorry for the long wait.  Merged (#2).

Thank you for the help!
